name: Deploy to QA

concurrency: 1

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_DEMO_WEST_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run pipeline update
        run: |
          set -o pipefail
          databricks bundle run dab_dlt_demo_job --refresh-all
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_DEMO_WEST_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging
